GET http://localhost:3001/room/1

###
POST http://localhost:3001/room/  HTTP/1.1
content-type: application/json

{
  "id": "coolid"
}

###
POST http://localhost:3001/room/ HTTP/1.1
content-type: application/json

{
  "id": []
}